<<<<<<< HEAD
- jekyll-feed
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-avatar
- jemoji
- jekyll-mentions
- jekyll-include-cache
=======
theme:jekyll-theme-dinky
>>>>>>> 31f984b34275794f09723defdd5905980f4bec4a
